name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set Xcode 12.4
        run: |
          sudo xcode-select -switch /Applications/Xcode_12.4.app

      - name: iOS Build 
        run: |
          xcodebuild \
            -project AmplitudeCore.xcodeproj \
            -scheme AmplitudeCore \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4'

      - name: macOS Build 
        run: |
          xcodebuild \
            -project AmplitudeCore.xcodeproj \
            -scheme AmplitudeCore \
            -sdk macosx \
            -destination 'platform=macosx' \

      - name: tvOS Build 
        run: |
          xcodebuild \
            -project AmplitudeCore.xcodeproj \
            -scheme AmplitudeCore \
            -sdk appletvsimulator \
            -destination 'platform=tvOS Simulator,name=Apple TV' \

      - name: iOS Tests
        run: |
          xcodebuild test \
            -project AmplitudeCore.xcodeproj \
            -scheme AmplitudeCore \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4'

      - name: macOS Tests
        run: |
          xcodebuild \
            -project AmplitudeCore.xcodeproj \
            -scheme AmplitudeCore \
            -sdk macosx \
            -destination 'platform=macosx' \
            test

      - name: tvOS Tests
        run: |
          xcodebuild \
            -project AmplitudeCore.xcodeproj \
            -scheme AmplitudeCore \
            -sdk appletvsimulator \
            -destination 'platform=tvOS Simulator,name=Apple TV' \
            test

